---  
   - name: Change root password
     user:
      name: root
      password: "{{ lookup('env', 'root_password') | password_hash(sha512') }}"
     when: "lookup('env', 'root_password') is not none"
